sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - npm install  
script:  
  - hexo clean
  - hexo g # generate static files
after_script:
  cd ./public
  git init
  git config user.name "jim"
  git config user.email "y_m_z@126.com"
  git add .
  git commit -m "add/edit"
  git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  echo "https://${GH_TOKEN}@${GH_REF}"
global:
  GH_REF: github.com/aji88/blog.git
