sudo: false
language: node_js
node_js:
- 10
cache: npm
branches:
  only:
  - master
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install
script:
- hexo clean
- hexo g
deploy:
  provider:script
  script:sh ./.travis/deploy.sh
  skip_cleanup:true
  on:
    branch:master

