sudo: false
language: node_js
node_js:
- 10
cache: npm
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_f07b2428cec6_key -iv $encrypted_f07b2428cec6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- export TZ='Asia/Shanghai'
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- cd ./.travis
- sh ./deploy.sh
